version: '3'

services:
  -sequelize:
    build: ./crud
    ports:
      - 3000:3000
    environment:
      - DB_USER=root
      - DB_PASS=password
      - DB_NAME=cliente
      - DB_HOST=db
    volumes:
      - ./crud:/app-crud
    container_name: cliente_crud
    restart: always
    depends_on:
      - db

  db:
    image: mysql
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=password
    restart: always
